### ISSUE TITLE
fix build

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkiverse-jna#2]
current issue is on native with : undefined reference to `Java_java_util_prefs_FileSystemPreferences_chmod'
it seems fix on graal...
https://github.com/oracle/graal/issues/2856
just wait release of quakus with graal 20.3

**Comment by gastaldi** [comment]
@all-contributors add @dufoli for code and maintenance

**Comment by Dufgui** [comment]
grallvm 20.3 is available, but quarkus wait fix from them to upgrade :  see detail https://github.com/quarkusio/quarkus/issues/13954

**Comment by dufoli** [comment]
error is fixed. error was remainig because build used a custom docker image which was 20.2 ...
so now this part is ok I arrive on next bug:
Caused by: java.lang.UnsatisfiedLinkError: Error looking up function 'atoi': com.sun.jna.Native.findSymbol(JLjava/lang/String;)J [symbol: Java_com_sun_jna_Native_findSymbol or Java_com_sun_jna_Native_findSymbol__JLjava_lang_String_2]
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
	at com.sun.jna.Library$Handler.invoke(Library.java:243)
	at com.sun.proxy.$Proxy217.atoi(Unknown Source)
	at io.quarkiverse.jna.test.JnaTestEndpoint.atoi(JnaTestEndpoint.java:27)

it come from test which use atoi method of clib.
3 build items exists for jni:

JniBuildItem : used to list library which is accesible.
JniRuntimeAccessBuildItem : used to lis java method accessible on jni side.
NativeImageResourceBuildItem: to add lib in final package.

and a config.

I think that we just need JniBuildItem but not sure.

**Comment by gastaldi** [comment]
@dufoli any progress on this issue?
